[tool.poetry]
name = "pulp-thing"
version = "0.1.0"
description = ""
authors = ["Richard Gong"]

[tool.poetry.dependencies]
python = "^3.7"
PuLP = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
